#! /bin/sh

sxhkd &

bspc config border_width        2
bspc config window_gap         2

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a URxvtWebpad sticky=on state=floating 
bspc rule -a URxvtScratchpad sticky=on state=floating 
bspc rule -a URxvtFred sticky=on state=floating 
bspc rule -a URxvtPrompt sticky=on state=floating 
